---
title: Sébastien Kuo, PgMP | Localization Professional
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
repository: kid-pro-kuo/kid-pro-kuo.github.io/
favicon: assets/favicon.ico
version: 2
name: Sébastien Kuo
email: sebastien@linguanaut.org
website: www.linguanaut.org
darkmode: true
twitter_username: kuo
github_username: kid-pro-kuo
facebook_username: sebastien.kuo
instagram_username: kid-pro-kuo
linkedin_username: sebastienkuo
additional_links:
- title: translation commons
  icon: fas fa-globe
  url: https://translationcommons.org
gtm: GTM-WPH29NB
google_analytics: UA-173917516-1
about_profile_image: images/profile.jpg
about_content: |
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
content:
- title: Projects and Publications
  layout: list
  content:
  - layout: top-middle
    title: Lorem ipsum dolor sit amet
    link: google.com/
    additional_links:
    - title: github link 1
      icon: fab fa-github
      url: github.com/
    quote: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
- title: Experience
  layout: list
  content:
  - layout: left
    title: StubHub, Inc.
    link: stubhub.com
    sub_title: Manager of Localization Engineering
    caption: December 2017 - August 2020
    quote: Solving 21st century problems by digging holes and making game changing
      products like the not a flamethrower
    description: Every company needs its networks properly administered and The Boring
      Company is no exception. Digging holes is hard and I play my part making sure
      the whole company stays connected. I lead a team of 5 people and enjoy driving
      the company to try new technologies.
  - layout: left
    title: StubHub, Inc.
    link: stubhub.com
    sub_title: Content Localization Manager
    caption: June 2015 - December 2017
    quote: Solving 21st century problems by digging holes and making game changing
      products like the not a flamethrower
    description: |
      - Developed and spearheaded localization strategy to drive international user growth metrics
      - Launched and supported a volunteer translator community
      - Drove localization project management incl. scoping, budgeting, resource allocation, scheduling, QA and risk management
      - Developed and enforced company-wide translation content quality control processes
      - Managed localization finance and vendor relationships
      - Forecast localization volume and budget needs
      - Collaborated with Product and Engineering teams to drive localization tooling development
      - Collaborated with Business Development and Data teams to influence localization strategy
      - Worked with external partners to solicit feedback, improve translation processes, and communicate the value of localization
  - layout: left
    title: Coursera
    link: coursera.org
    sub_title: Localization Program Manager
    caption: March 2014 - June 2015
    quote: Solving 21st century problems by diging holes and making game changing
      products like the *not a flamethrower*
    description: |
      - Developed and spearheaded localization strategy to drive international user growth metrics
      - Launched and supported a volunteer translator community
      - Drove localization project management incl. scoping, budgeting, resource allocation, scheduling, QA and risk management
      - Developed and enforced company-wide translation content quality control processes
      - Managed localization finance and vendor relationships. Forecast localization volume and budget needs
      - Collaborated with Product and Engineering teams to drive localization tooling development
      - Collaborated with Business Development and Data teams to influence localization strategy
      - Worked with external partners to solicit feedback, improve translation processes, and communicate the value of localization
  - layout: left
    title: Twitter, Inc.
    link: twitter.com
    sub_title: Localization Project Manager, Mobile Platforms
    caption: June 2012 - March 2014
    quote: Solving 21st century problems by diging holes and making game changing
      products like the *not a flamethrower*
    description: |
      - Championed the needs of Twitter’s growing international communities
      - Managed the localization for mobile products : iOS, Android, mobile web, SMS, OEM partnerships
      - Injected international user perspective throughout the product development cycle
      - Reviewed and advised engineering and product teams on internationalization best practices
      - Determined the most appropriate localization solution for each product and related marketing assets, sourcing from community translation and vendor resources
      - Created a linguistic QA testing cadence (with test plans) via community or third-party testing vendors
      - Triaged international user feedback and provided regular reports to product managers
      - Gathered and presented weekly metrics on international user satisfaction
      - Created localization specifications and guidelines for OEM partner developers
      - Created product requirements and developed improvements to internal translation platform
  - layout: left
    title: Etsy, Inc.
    link: etsy.com
    sub_title: Localization Project Manager
    caption: February 2010 - June 2012
    quote: The limits of my language mean the limits of my world.
    description: |
      - Drafted and implemented localization plan for successive language support of Etsy.com
      - Managed a team of community managers and linguists
      - Defined localization workflows and standards for Etsy including delivery requirements and LQA
      - Designed internationalization and localization processes into the product development cycle
      - Triaged localization bugs and deploy fixes where appropriate
      - Maintained localization quality through product development oversight and LQA tests
      - Defined product requirements and oversee feature improvements to internal translation tools
      - Gathered metrics to determine future localization needs and measure effectiveness of current efforts
  - layout: left
    title: Etsy, Inc.
    link: etsy.com
    sub_title: Lead Trust & Safety Agent
    caption: July 2009 - February 2010
    quote: Your assumptions are your windows on the world. Scrub them off every once in a while, or the light won't come in.
    description: |
      - Identified and reduced ecommerce fraud within an online marketplace through behavioral targeting
      - Interpreted, influenced, and applied policy to member / transaction disputes
      - Researched competitive practices and industry standards in order to consistently improve marketplace trust
      - Drove policy changes and trust building initiatives based on customer feedback with product and legal teams
      - Specced and managed the creation and improvement of trust and safety backend and frontend tools with engineering team
      - Built a Trust & Safety team through data driven feedback and evangelizing customer needs within the company’s mission
  - layout: left
    title: Etsy, Inc.
    link: etsy.com
    sub_title: Customer Support Representative
    caption: January 2009 - July 2009
    quote: He who works with his hands and his head and his heart is an artist.
    description: |
      - Educated members on the basics of using Etsy.com as well as tips to improve productivity or user experience
      - Helped to create a curriculum as well as mentored new customer support representatives
      - Promoted metrics gathering tools in order to drive rep efficiency and customer satisfaction perceptions
      - Handled large volumes of inbound customer support requests via email and live chat
  - layout: left
    title: European Parliament
    link: europarl.europa.eu
    sub_title: Research Assistant for the RH Timothy Kirkhope, MEP
    caption: January 2006 - June 2008
    quote: _In varietate concordia_ | United in diversity
    description: |
      - Provided administrative support to the office of the MEP
      - Drafted responses to all constituents’ correspondence regarding personal and party motivations in a wide range of policymaking areas
      - Researched and drafted parliamentary questions, motions and reports in MEP’s areas of concern
- title: Education
  layout: list
  content:
  - layout: left
    title: Vrije Universiteit Brussel
    caption: 2007 - 2008
    sub_title: MA, Comparative Linguistics
  - layout: left
    title: The George Washington University
    caption: 2003 - 2007
    sub_title: BA, International Affairs
- title: More About Me
  layout: text
  content: |
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur:
    - Rock climbing
    - Gaming
    - Knitting
    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

footer_show_references: true
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- lib/
- scripts/
- docker-compose.yml
